[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
shared = { path = "../shared" }
sqlx.workspace = true
chrono.workspace = true
uuid.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
jsonwebtoken.workspace = true
argon2.workspace = true
async-trait.workspace = true
aws-sdk-sesv2.workspace = true
aws-config.workspace = true
genpdf.workspace = true

[dev-dependencies]
tokio.workspace = true
